kind: pipeline
name: CI
steps:
    - name: testing
      image: python:3.8.3-buster
      commands:
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
        - pytest
        