[tool.black]
line-length = 119

[tool.isort]
line_length = 119
length_sort = true
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
addopts = "--cov=jeopardy --cov-report html --cov-report xml"
testpaths = [ "tests" ]

[tool.pylint.'FORMAT']
max-line-length = 119
